### ISSUE TITLE
Error Tracking? Ex: Rollbar

### ISSUE THREAD

**Issue by metaskills** [customink/lambdakiq#2]
This should work out of the box but we may need to do a few things. Need to take a look at what other ActiveJob backends do or if each error vendor hooks into each backend individually or does it do instrument ActiveJob as a whole?

**Comment by nitsujri** [comment]
Currently using Rollbar in a discovery project.

Rollbar doesn't have a direct [ActiveJob async handler](https://docs.rollbar.com/docs/activejob-integration). 

The way I've done it in the discovery project is [using sucker_punch](https://docs.rollbar.com/docs/sucker_punch-integration) and using Rollbar's `ActiveJob` wrapper above.

For Rollbar, there would need to be a direct integration/plugin if we wanted Lambdakiq to be the async handler like [Sidekiq](https://docs.rollbar.com/docs/sidekiq-integration)

**Comment by metaskills** [comment]
>  there would need to be a direct integration/plugin if we wanted Lambdakiq to be the async handler like Sidekiq

So one thing Lambdakiq did different than Sidekiq is that we conform more strictly to the ActiveJob interface. So I'm thinking to support any error tracker we could simple document something like this?

```ruby
class ApplicationJob < ActiveJob::Base
  include Lambdakiq::Worker
  queue_as ENV['JOBS_QUEUE_NAME']
  rescue_from, Exception do |e|
    Rollbar.error(
      exception,
      job: self.class.name,
      job_id: job_id,
      use_exception_level_filters: true,
      arguments: arguments
    )
    raise exception
  end  
end
```

**Comment by nitsujri** [comment]
Ah I believe we're talking about 2 different things. 

- Capturing errors thrown in a background job/activejob
- Sending errors to Rollbar async

With Rollbar, Capturing errors in [ActiveJob](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/active_job.rb#L4) is already solved by adding [`include Rollbar::ActiveJob`](https://docs.rollbar.com/docs/activejob-integration) which is really similar as the code above.

A direct Lambdakiq integration with Rollbar (or anyone else) would allow sending the job async using itself without the need of [`sucker_punch`](https://github.com/brandonhilkert/sucker_punch) or threading.

Here's the snippet from the rollbar.rb generated initializer:

```
# Enable asynchronous reporting (uses girl_friday or Threading if girl_friday
# is not installed)
# config.use_async = true
# Supply your own async handler:
# config.async_handler = Proc.new { |payload|
#  Thread.new { Rollbar.process_from_async_handler(payload) }
# }

# Enable asynchronous reporting (using sucker_punch)
# config.use_sucker_punch
```

My off-the-cuff recommendation would be, do nothing (or just recommend using threading/sucker_punch, not girl_friday [no longer maintained]).

Thoughts?

**Comment by metaskills** [comment]
> Sending errors to Rollbar async

As far as I know this is not possible in Lambda. I've tried doing async ActiveJobs before with sucker punch and was never able to get it to work because nothing can happen after the handler is finished. For async Rollbar from a background job, I'm not sure I understand that optimization. Background jobs are already out of band of critical work, assuming there was a way to optimize that wouldn't the only way to do it from Lambda is to make another job from a job?

**Comment by nitsujri** [comment]
Oh that's SUPER interesting about threaded items closing after the handler finished. 

It could explain some connection errors that I'm getting:

```
Failsafe from rollbar-gem. OpenSSL::SSL::SSLError: "SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A" in /var/lang/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': error in process_item

Failsafe from rollbar-gem. Net::OpenTimeout: "execution expired" in /var/lang/lib/ruby/2.7.0/net/http.rb:960:in `initialize': error in process_item
```

I've never seen these errors outside of lambda before, and I don't have a great explanation for them - this is the best one so far. But I also wonder how I got these if the handler already finished execution... hrm...

Back to the original topic - this actually makes a strong recommendation for a direct async handler for Rollbar using Lambdakiq.

Scenarios:

- Controller -> Generates Error -> Hands Error to Lambdakiq Rollbar "sender"
- ActiveJob -> Generates Error -> Hands Error to Lambdakiq Rollbar "sender"

Agreed that async is mostly for not blocking frontend work.

A direct Rollbar handler would also solve the "nothing can happen after the handler is finished".

**Comment by metaskills** [comment]
Ah, OK I see now. So we have never really optimized rollbar to be async even in the Controller -> Error scenario. Rollbar is typically very fast to respond and in an error situation we just take that small hit. 

If things need to be async and close to long running processes (unlike Lambda) then it might be worth digging into how/why things do not work as expected. I mean, I kind of know why, the Runtime just does not want you doing things outside the Handler or else you would have free compute.

Maybe this is an opportunity to look at Lambda Extensions API? https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html In the diagrams there you can see how they work. Here is an except from the Invoke section:

> During the invocation, external extensions run in parallel with the function. They also continue running after the function has completed. This enables you to capture diagnostic information or send logs, metrics, and traces to a location of your choice.

I've always wondered when might be a good time to learn this stuff more. Many vendors tie into it. In this post (https://dev.to/aws-heroes/using-new-relic-apm-with-rails-on-aws-lambda-51gi) I talked about how you have to flush New Relics data at the end of each request in a `handler` ensure. Wonder if Lamby should have a Lambda extension to help with stuff like this?

**Comment by metaskills** [comment]
But stuff like this makes me think it is a siz and half dozen situation.

> Note that there is no independent post-invoke phase. The duration is the sum of all invocation time (runtime + extensions) and is not calculated until the function and all extensions have finished executing.

**Comment by nitsujri** [comment]
> Rollbar is typically very fast to respond and in an error situation we just take that small hit.

To be pedantic, a production environment can't rely on an external service being up for critical processes. Rollbar will eventually go down.

Probably the reason Rollbar doesn't go through an ActiveJob interface is there is the potential for generating infinite calls if the ActiveJob interface fails in just the right way. In Lambda + SQS's case, get expensive fast. I see now that direct plugins are the way to go.

I also think that Lambda Extensions API probably overkill/not the right solution. While the [Rollbar Plugin DSL](https://docs.rollbar.com/docs/gem-plugins) seems straight forward enough to integrate Lambdakiq directly, [Reading the Sidekiq plugin](https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/plugins/sidekiq/plugin.rb) - I don't understand how it calls sidekiq directly though =/

Separately, Lambda [pauses background processes](https://zaccharles.medium.com/what-happens-to-running-threads-when-a-lambda-finishes-executing-312a6f5757b4) and allows them to continue if the same container gets reused, which fully explains my errors. Thanks for pointing me that way.

**Comment by metaskills** [comment]
> To be idealistic, a production environment can't rely on an external service being up for critical processes. Rollbar will eventually go down.

I very much agree. Another way to look at this is "critical failing processes" because if the application is working no errors are generated. Also, there is a config to reduce Rollbars open timeout so if things were ever in "double trouble" (errors in service and Rollbar down) then the impact is reduced and errors are ignored. 

> Probably the reason Rollbar doesn't go through an ActiveJob interface is there is the potential for generating infinite calls 

Good point, I see it now. But, if I am reading the code right, then you can remove that concern by doing the following?

```ruby
class ApplicationJob < ActiveJob::Base
  include Lambdakiq::Worker
  queue_as ENV['JOBS_QUEUE_NAME']

  rescue_from, Exception do |e|
    Rollbar.silenced do
      Rollbar.error(
        exception,
        job: self.class.name,
        job_id: job_id,
        use_exception_level_filters: true,
        arguments: arguments
      )
      raise exception
    end
  end
end
```

> I also think that Lambda Extensions API probably overkill/not the right solution.

Very possible, but given it is async to the handler process... it does seem really cool and maybe straightforward. If I had to pick my time I might ship the code above. But if I were Rollbar I might update their aging Ruby docs (https://docs.rollbar.com/docs/aws-lambda-ruby) to something more modern and maybe do an Lambda Extension.

cc @waltjones

**Comment by metaskills** [comment]
I created this issue there too. https://github.com/rollbar/rollbar-gem/issues/1042

**Comment by nitsujri** [comment]
I might have a **hacky** workaround that isn't that much code.

``` ruby
# config/rollbar.rb
config.use_async = true
# Supply your own async handler:
config.async_handler = Proc.new { |payload|
  called_by_activejob = Thread.current.backtrace.any? { |line| line.match?(/app\/jobs\/.+.rb/) }
  if called_by_activejob
    # We're in a background job, send directly
    Rollbar.process_from_async_handler(payload)
  else
    # Handle with ActiveJob
    SendToRollbarJob.perform_async(payload)
  end
}

# app/jobs/send_to_rollbar_job.rb
class SendToRollbarJob < ApplicationJob
  lambdakiq_options retry: 13

  def perform(*args)
    Rollbar.process_from_async_handler(payload)
  end
end
```

**Benefits**
- Foreground jobs get async'ed via ActiveJob & ActiveJob is synchronous. 
- Also, handles Rollbar.silence as part of the `include Rollbar::ActiveJob` since it goes through `process_from_async_handler`

Scenarios:

```
- Error in Controller/Model/etc => 
  - Rollbar.async_handler => 
    - SendToRollbarJob (Lambdakiq) => 
      - Rollbar.process_from_async_handler =>
        - Rollbar.silence =>
          - Rollbar.process_item => ...

- Error in BackgroundJob => 
  - Rollbar.async_handler =>  
    - Rollbar.process_from_async_handler =>
      - Rollbar.silence =>
        - Rollbar.process_item => ...
```

**Hacky**
- We're looking at filenames instead of classes
- Assumes all background classes lives inside `./app/jobs` (very brittle)

**Comment by metaskills** [comment]
That does seem clean! Question, did you see my notes here for Lambda Extension's new annulment for early returns? https://github.com/customink/lamby/issues/98 The question I'd like to ask next is maybe we should make a simple Lambda Extension for Ruby to be the equivalent of SuckerPunch but for Lambda?

**Comment by metaskills** [comment]
The extension did happen. https://github.com/customink/lambda_punch
