### ISSUE TITLE
Cloudformation template

### ISSUE THREAD

**Issue by mackensen** [customink/lambdakiq#21]
We're interested in using this project at my institution and we'd prefer to use a Cloudformation template (or a CDK project) to deploy the AWS resources independently of the application. It's not clear to me whether that's possible or, if it is, exactly what we would need to create. Thank you for any guidance.

**Comment by metaskills** [comment]
The ruby code cares not who created the resources. You can create them via ClickOps to any other IaC tool. What is important is that you ensure your Lambda function has the the IAM perms needed (https://github.com/customink/lambdakiq#iam-permissions) to work with the queue. The ruby code also needs the name of the SQS queue to work with. This can be an environment variable or hard coded via the `queue_as` setter.
